### PR TITLE
Feature | Mount entire project and load multiple config files

### LINKED ISSUE #90: Support config files other than the predefined ones
## What? 

Support config files other than the predefined ones

- Currently we only support the following config files: `common.tfvars`, `backend.tfvars` and `account.tfvars`
- Ideally, we should be able to create any config files we want and the CLI should be able to pick them up and pass them to Terraform automatically.
- Have a way to build several `.tfvars` focused on specific things and not have to pile them up in 1 or 2 files.

## How?

In the past we mounted the folders so it was a bit more flexible (now we have a stricter approach)

- **Opt-1** | Making the configs more flexible, directly mount the `/config` and `/account/config` directory and pass all `.tfvar` that are in there to terraform.
- **Opt-2** | Maybe setting up the whole project is the easiest thing to do.

## Why? 

- https://github.com/binbashar/le-tf-infra-aws/issues/291 
- Regarding the symlinks issue, some @angelofenoglio questions
    -  Would riding the whole project be an option? 
    - Or the idea of limiting it to the layer exclusively was initially given for something specific or just to try to be as restrictive as possible?

### PR DESCRIPTION
**Pull request by angelofenoglio**
## What?
* Mount whole project instead of only the current layer.
* Load all `.tfvars` files found in global and account config directory when running a terraform command that requires it.

## Why?
* Allows for greater flexibility when working in a project.
* Enables future planned features.

## References
* Closes #90

### CODE REVIEW

**Review by exequielrafaela — APPROVED** [review]
@angelofenoglio This is great! 🚀

**Comment by thpham** [comment]
hello, this PR seems to make the following documentation outdated: https://leverage.binbash.com.ar/first-steps/leverage-project-setup/#fill-in-the-configuration-file

I had few problems in the bootstrap credential section.

**Comment by exequielrafaela** [comment]
@thpham thanks for your comment. In order to help you here it would be great if you could open an associated issue with more detail at https://github.com/binbashar/le-ref-architecture-doc/issues 

It would be great if you could also join us on our Binbash Leverage community Slack channel https://join.slack.com/t/binbashar/shared_invite/zt-fw1692b6-9k4ADsWJ47lKacszphXM1w in order to try to fix this ASAP.

Thanks again for your valuable collaboration here, and looking forward to your updates no this issue.

CC: @binbashar/leverage-ref-architecture-aws-admin @binbashar/leverage-ref-architecture-aws-dev

**Comment by exequielrafaela** [comment]
@thpham I think we've already found the issue related with your comment @angelofenoglio we'll collab with the PR ASAP 💪🏼 

CC: @diego-ojeda-binbash

**Comment by exequielrafaela** [comment]
@diego-ojeda-binbash let's consider we still new to fix the terraform image version in the template from `1.0.9` to `1.1.9` => https://github.com/binbashar/le-tf-infra-aws-template/blob/master/template/build.env.template

CC: @angelofenoglio @lgallard @rodriguez-matias

**Pull request merged**
